### ISSUE TITLE
Importing a group without e-mail defined in groups resource block

### ISSUE THREAD

**Issue by caspereijkens** [Axual/terraform-provider-axual#23] opened 2023-08-17 14:22 UTC
I am currently testing v1.1.3. I tried importing an Axual group into a TF resource and I got:

```
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to module.groups_shared.axual_group.<redacted>, provider "provider[\"registry.terraform.io/axual/axual\"].shared" produced an unexpected new value: .email_address: was null, but now cty.StringVal("").
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
```

The group resource looks like:
```
resource "axual_group" "<redacted>" {
  name          = "<redacted>"
  members = [
    <redacted>
  ]
}
```
Note, that e-mail here is not defined but since it is optional, that should not be a problem.
It seems like the import still worked though but still worth it to share I think.

**Comment by kasparAxual** [comment] 2023-11-07 12:03
I have closed this issue due to inability to reproduce it, if you are able to reproduce please open a new issue

**Closed by kasparAxual** 2023-11-07 12:03 UTC
